version: "3"
services:
  database:
    image: mysql:5.7
    container_name: database
    network_mode: "host"
    command: --init-file /data/application/init.sql
    volumes:
        - ./db/init.sql:/data/application/init.sql
    environment:
        TZ: "America/Edmonton"
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: life
        MYSQL_USER: user
        MYSQL_PASSWORD: user
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
        timeout: 20s
        retries: 10
    
  backend:
    image: essamgouda97/ayd_backend
    container_name: backend
    network_mode: "host"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./submodules/ayd_backend:/backend
      - ./logs:/logs
  
  dev-bot:
    image: essamgouda97/ayd_cj
    container_name: dev-bot
    network_mode: "host"
    working_dir: /bot
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./submodules/ayd_cj:/bot
      - ./logs:/logs
